"""empty message

Revision ID: 04dd3161678e
Revises: 94e669167bbe
Create Date: 2020-11-19 10:56:03.774374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dd3161678e'
down_revision = '94e669167bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(length=255), nullable=True),
    sa.Column('v0', sa.String(length=255), nullable=True),
    sa.Column('v1', sa.String(length=255), nullable=True),
    sa.Column('v2', sa.String(length=255), nullable=True),
    sa.Column('v3', sa.String(length=255), nullable=True),
    sa.Column('v4', sa.String(length=255), nullable=True),
    sa.Column('v5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
