"""empty message

Revision ID: 19d5ef71883b
Revises: a9a6f4fa6fe5
Create Date: 2020-11-19 15:18:12.435143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19d5ef71883b'
down_revision = 'a9a6f4fa6fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('operation_name_cn', sa.String(length=80), nullable=False))
    op.add_column('operation', sa.Column('operation_name_en', sa.String(length=80), nullable=False))
    op.drop_index('operation_name', table_name='operation')
    op.create_unique_constraint(None, 'operation', ['operation_name_cn'])
    op.create_unique_constraint(None, 'operation', ['operation_name_en'])
    op.drop_column('operation', 'operation_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('operation_name', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'operation', type_='unique')
    op.drop_constraint(None, 'operation', type_='unique')
    op.create_index('operation_name', 'operation', ['operation_name'], unique=True)
    op.drop_column('operation', 'operation_name_en')
    op.drop_column('operation', 'operation_name_cn')
    # ### end Alembic commands ###
