"""empty message

Revision ID: 6e3273973837
Revises: 19d5ef71883b
Create Date: 2020-11-19 15:40:57.672464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e3273973837'
down_revision = '19d5ef71883b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_name_cn', sa.String(length=80), nullable=False),
    sa.Column('operation_name_en', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_name_cn'),
    sa.UniqueConstraint('operation_name_en')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_name'),
    sa.UniqueConstraint('url')
    )
    op.drop_index('operation_name_cn', table_name='operation')
    op.drop_index('operation_name_en', table_name='operation')
    op.drop_table('operation')
    op.drop_index('resource_name', table_name='resource')
    op.drop_index('url', table_name='resource')
    op.drop_table('resource')
    op.drop_index('domain_name', table_name='domain')
    op.drop_table('domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('domain_name', 'domain', ['domain_name'], unique=True)
    op.create_table('resource',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('resource_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('url', 'resource', ['url'], unique=True)
    op.create_index('resource_name', 'resource', ['resource_name'], unique=True)
    op.create_table('operation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('operation_name_cn', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('operation_name_en', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('operation_name_en', 'operation', ['operation_name_en'], unique=True)
    op.create_index('operation_name_cn', 'operation', ['operation_name_cn'], unique=True)
    op.drop_table('resources')
    op.drop_table('operations')
    op.drop_table('domains')
    # ### end Alembic commands ###
